version: "3.8"

services:
  node:
    build:
      context: "node/"
    image: node-app
    env_file:
      - "./node/.env"
    ports:
      - 3000:5000

  

  vue:
    build:
      context: "vue/"
    image: vue-app
    env_file:
      - "./vue/.env"
    ports:
      - 6000:3000
      