export const ALL_PRODUCTS= 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS' 

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'

export const REMOVE_PRODUCT= 'REMOVE_PRODUCT'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'

export const ALL_SHOPS= 'ALL_SHOPS'
export const ALL_SHOPS_SUCCESS = 'ALL_SHOPS_SUCCESS' 

export const SHOP_BY_ID = 'SHOP_BY_ID'
export const SHOP_BY_ID_SUCCESS = 'SHOP_BY_ID_SUCCESS'

export const ADD_SHOP= 'ADD_SHOP'
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS'

export const UPDATE_SHOP = 'UPDATE_SHOP'
export const UPDATE_SHOP_SUCCESS = 'UPDATE_SHOP_SUCCESS'


export const REMOVE_SHOP= 'REMOVE_SHOP'
export const REMOVE_SHOP_SUCCESS = 'REMOVE_SHOP_SUCCESS'



export const ALL_TRANSCTIONS= 'ALL_TRANSCTIONS'
export const ALL_TRANSCTIONS_SUCCESS = 'ALL_TRANSCTIONS_SUCCESS'

export const TRANSCTIONS_BY_ID = 'TRANSCTIONS_BY_ID'
export const TRANSCTIONS_BY_ID_SUCCESS = 'TRANSCTION_BY_ID_SUCCESS'




export const ALL_REPORTS = 'ALL_REPORTS'
export const ALL_REPORTS_SUCCESS = 'ALL_REPORTS_SUCCESS'

export const REPORTS_BY_ID = 'REPORTS_BY_ID'
export const REPORTS_BY_ID_SUCCESS = 'REPORTS_BY_ID_SUCCESS'



export const ALL_CUSTOMERS= 'ALL_CUSTOMERS'
export const ALL_CUSTOMERS_SUCCESS = 'ALL_CUSTOMERS_SUCCESS' 


export const CUSTOMERS_BY_ID = 'CUSTOMER_BY_ID'
export const CUSTOMERS_BY_ID_SUCCESS = 'CUSTOMERS_BY_ID_SUCCESS'


export const ALL_STAFF = 'ALL_STAFF'
export const ALL_STAFF_SUCCESS = 'ALL_STAFF_SUCCESS'

export const ADD_STAFF = 'ADD_STAFF'
export const ADD_STAFF_SUCCESS = 'ADD_RECRUITER_SUCCESS'

export const UPDATE_STAFF = 'UPDATE_STAFF'
export const UPDATE_STAFF_SUCESS = 'UPDATE_STAFF_SUCESS'

export const REMOVE_STAFF= 'REMOVE_STAFF'
export const REMOVE_STAFF_SUCESS = 'REMOVE_STAFF_SUCESS'
